# ── Fuzzel App Launcher ────────────────────────────────────

[main]
terminal = kitty
dpi-scale = 1

[colors]
background = 000000ff
text = ffffffcc
match = ff6666ff
selection = 333333ff
selection-text = ffffffcc
border = ffffffcc

[border]
width = 1
radius = 0

[layout]
width = 50
lines = 10
